apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-01-06T07:17:15Z"
  generation: 1
  labels:
    app: go-webapp
  name: go-webapp
  namespace: default
  resourceVersion: "132554"
  uid: d7961026-507d-4d30-b6b0-2688321c6284
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-webapp
    spec:
      containers:
      - image: vansh955/go-webapp:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: go-webapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-01-06T07:17:15Z"
    lastUpdateTime: "2025-01-06T07:17:15Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2025-01-06T07:17:15Z"
    lastUpdateTime: "2025-01-06T07:17:15Z"
    message: ReplicaSet "go-webapp-6dcd7bf4c6" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
