apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: goweb-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: goweb.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-websvc
                port:
                  number: 80
