apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-webapp
  name: go-websvc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-webapp
  type: NodePort
status:
  loadBalancer: {}
